name: Compile and Update LaTeX Resume

# Trigger the workflow on push events to the 'resume/**' directory, on a schedule, and manually through workflow_dispatch
on:
  push:
    paths:
      - 'resume/**'
  schedule:
    - cron: '0 19 * * 1' # Runs every Monday at 19:00 UTC
  workflow_dispatch:

jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    # Step 1: Checkout the repository
    - name: Set up Git repository
      uses: actions/checkout@v4

    # Step 2: Compile the LaTeX document to PDF
    - name: Install LaTeX
      run: |
          sudo apt-get update
          sudo apt-get install -y aptitude
          sudo aptitude update
          sudo aptitude install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

    - name: Compile LaTeX document
      run: |
          cd resume
          pdflatex jaman-uddin.tex

    # Step 3: Convert the PDF to a high-quality image
    - name: Install Poppler (pdftoppm)
      run: |
          sudo aptitude update
          sudo aptitude install -y poppler-utils

    - name: Convert PDF to PNG
      run: |
          pdftoppm resume/jaman-uddin.pdf resume/jaman-uddin -png -r 300
          mv resume/jaman-uddin-1.png resume/jaman-uddin.png

    # Step 4: Configure Git user and email
    - name: Configure Git
      run: |
          git config --local user.email "zamaan.md19@gmail.com"
          git config --local user.name "RootProgrammer"
    
    # Step 5: Update or Create a Branch and Push Changes
    - name: Update or Create Branch and Push Changes
      run: |
        # Fetch all branches from the remote to ensure git is aware of the branch if it exists
        git fetch origin
        # Attempt to checkout the branch if it exists, or create it if it doesn't
        if git checkout update-resume-$(date +%Y-%m-%d); then
          echo "Branch already exists. Checked out and pulling latest changes."
          git pull origin update-resume-$(date +%Y-%m-%d)
        else
          echo "Creating a new branch."
          git checkout -b update-resume-$(date +%Y-%m-%d)
        fi
        # Add changes
        git add resume/jaman-uddin.pdf resume/jaman-uddin.png
        git commit -m "Automatically update compiled resume PDF and PNG"
        # Push changes, using --force-with-lease as a safer alternative to --force
        git push --force-with-lease origin update-resume-$(date +%Y-%m-%d)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Create a Pull Request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update compiled resume PDF and PNG
        title: "Automatically update compiled resume PDF and PNG"
        body: "This is an auto-generated PR to update the compiled PDF and PNG files."
        branch: update-resume-$(date +%Y-%m-%d) # Ensure this matches the branch created above
        
