name: Compile and Update LaTeX Resume

# Trigger the workflow on push events to the 'resume/**' directory, on a schedule, and manually through workflow_dispatch
on:
  push:
    paths:
      - 'resume/**'
  schedule:
    - cron: '0 2 * * 1-5' # Runs at 02:00 on every day-of-week from Monday through Friday
  workflow_dispatch:

jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    # Step 1: Checkout the repository
    - name: Set up Git repository
      uses: actions/checkout@v4

    # Change to the resume directory before running the LaTeX action
    # - name: Change to resume directory
    #   run: cd resume

    # Step 2: Compile the LaTeX document to PDF
    - name: Install LaTeX
      run: |
          sudo apt-get update
          sudo apt-get install -y aptitude
          sudo aptitude update
          sudo aptitude install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

    - name: Compile LaTeX document
      run: |
          cd resume
          pdflatex jaman-uddin.tex
    
    # Step 3: Convert the PDF to a high-quality image
    - name: Install Poppler (pdftoppm)
      run: |
          sudo aptitude update
          sudo aptitude install -y poppler-utils

    - name: Convert PDF to PNG
      run: |
          pdftoppm resume/jaman-uddin.pdf resume/jaman-uddin -png -r 300
          mv resume/jaman-uddin.png resume/jaman-uddin.png      

    # Step 3: Commit the compiled PDF back to the repository
    - name: Commit compiled PDF and PNG
      uses: stefanzweifel/git-auto-commit-action@v5  # Uses the Git Auto-Commit Action to commit changes
      with:
        commit_message: "Automatically update compiled resume PDF and PNG" # The commit message
        file_pattern: resume/jaman-uddin.pdf resume/jaman-uddin.png # The path to the compiled PDF and generated PNG to commit
        branch: main # The branch to commit to
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
