name: Compile and Update LaTeX Resume

# Trigger the workflow on push events to the 'resume/**' directory, on a schedule, and manually through workflow_dispatch
on:
  push:
    paths:
      - 'resume/**'
  schedule:
    - cron: '0 2 * * 1-5' # Runs at 02:00 on every day-of-week from Monday through Friday
  workflow_dispatch:

jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    # Step 1: Checkout the repository
    - name: Set up Git repository
      uses: actions/checkout@v4

    # Step 2: Compile the LaTeX document to PDF
    - name: Install LaTeX
      run: |
          sudo apt-get update
          sudo apt-get install -y aptitude
          sudo aptitude update
          sudo aptitude install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

    - name: Compile LaTeX document
      run: |
          cd resume
          pdflatex jaman-uddin.tex

    # Step 3: Convert the PDF to a high-quality image
    - name: Install Poppler (pdftoppm)
      run: |
          sudo aptitude update
          sudo aptitude install -y poppler-utils

    - name: Convert PDF to PNG
      run: |
          pdftoppm resume/jaman-uddin.pdf resume/jaman-uddin -png -r 300
          mv resume/jaman-uddin-1.png resume/jaman-uddin.png

    # Create a new branch and commit changes
    - name: Create a new branch and commit PDF and PNG
      run: |
        git checkout -b update-resume-$(date +%Y-%m-%d)
        git add resume/jaman-uddin.pdf resume/jaman-uddin.png
        git commit -m "Automatically update compiled resume PDF and PNG"
        git push origin update-resume-$(date +%Y-%m-%d)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
