name: Compile LaTeX Resume

on:
  push:
    paths:
      - 'resume/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: latex_resume/jaman-uddin.tex
        
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: latex_resume/jaman-uddin.pdf
